[update]
tasks = ["code", "normalize"]

[update.code]
codePaths = ["."]
localizablePaths = ["."]
additive = false
defaultToKeys = false
unstripped = false

[update.normalize]
path = "."
harmonizeWithSource = true
sortByKeys = true
